name: Updater

on:
  schedule:
    - cron: '0 */1 * * *'
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - run: curl -s -L ${{secrets.UPDATER}} -o updater.py
    - run: curl -s -L ${{secrets.TXT1}} -o txt1.txt
    - run: curl -s -L ${{secrets.TXT2}} -o txt2.txt
    - run: python updater.py
    - run: rm txt1.txt txt2.txt updater.py
    - name: Commit files
      run: |
        git config --local user.email ${{ secrets.GIT_EMAIL }}
        git config --local user.name ${{ secrets.GIT_NAME }}
        git commit -am "Updated List"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
